# Generated by Django 4.0.4 on 2022-05-25 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phoneNumber', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('deathDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['authorID'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('publishDate', models.DateField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('soldCount', models.PositiveIntegerField(blank=True, null=True)),
                ('auhtorID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.author')),
                ('categoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
            ],
            options={
                'ordering': ['bookID'],
            },
        ),
    ]
